from .usuario_repository import UsuarioRepository
from .entrenador_repository import trainerRepository
from .sucursales_repository import SucursalesRepository
from .membresias_repository import MembresiaRepository
from .tipo_clases_repository import TipoClasesRepository
from .clases_repository import ClaseRepository